apiVersion: v1
kind: Service
metadata:
    name: "corekubecluster-1779"
    labels:
        app: "corekubecluster-1779"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "corekubecluster-1779"